version: '3'

services:
  app:
    build: ./docker/app
    volumes:
      - .:/var/www:cached
  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - 8888:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
